version: '3.9'

services:
  qdrant_node_1:
    image: qdrant/qdrant:${QDRANT_VERSION}
    ports:
      - "6333:6333"
    expose:
      - "6335"
    volumes:
      - ./custom_config.yaml:/qdrant/config/production.yaml
      - ./qdrant_storage/qdrant_node_1:/qdrant/storage
    command: ./qdrant --uri 'http://qdrant_node_1:6335'

  qdrant_node_2:
    image: qdrant/qdrant:${QDRANT_VERSION}
    ports:
      - "6400:6333"
    expose:
      - "6335"
    volumes:
      - ./custom_config.yaml:/qdrant/config/production.yaml
      - ./qdrant_storage/qdrant_node_2:/qdrant/storage
    command: ./qdrant --bootstrap 'http://qdrant_node_1:6335'
    depends_on:
      - qdrant_node_1

  qdrant_node_3:
    image: qdrant/qdrant:${QDRANT_VERSION}
    ports:
      - "6401:6333"
    expose:
      - "6335"
    volumes:
      - ./custom_config.yaml:/qdrant/config/production.yaml
      - ./qdrant_storage/qdrant_node_3:/qdrant/storage
    command: ./qdrant --bootstrap 'http://qdrant_node_1:6335'
    depends_on:
      - qdrant_node_1
